import createFetchClient from 'openapi-fetch'
import createClient from 'openapi-react-query'
import { QueryClient } from '@tanstack/react-query'
import type { paths } from './v1' // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: 'http://127.0.0.1:8000/',
})

export const $api = createClient(fetchClient)
export const queryClient = new QueryClient()
