"""Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = os.getenv("LOG_DIR", "/tmp/log/phenomate")
os.makedirs(LOG_DIR, exist_ok=True)

# Celery settings
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "amqp://guest:guest@localhost")

#: Only add pickle to this list if your broker is secured
#: from unwanted access (see userguide/security.html)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

CELERY_WORKER_HIJACK_ROOT_LOGGER = False    # prevent Celery from altering root logger
CELERY_WORKER_REDIRECT_STDOUTS = True      # send print/stdout/stderr into logger
CELERY_WORKER_REDIRECT_STDOUTS_LEVEL = 'INFO'

CELERY_WORKER_LOG_FORMAT = (
    '%(asctime)s %(levelname)s %(name)s %(processName)s '
    '[%(filename)s:%(lineno)d] %(message)s'
)
CELERY_WORKER_TASK_LOG_FORMAT = (
    '%(asctime)s %(levelname)s %(name)s [task:%(task_name)s id:%(task_id)s] %(message)s'
)


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s %(levelname)s %(name)s [%(process)d] %(module)s:%(lineno)d - %(message)s",
        },
        "simple": {"format": "%(levelname)s %(message)s"},
    },
    "handlers": {
        # Django app file
        "django_file": {
            "class": "logging.handlers.WatchedFileHandler",
            "filename": os.path.join(LOG_DIR, "django.log"),
            "formatter": "verbose",
            "level": "INFO",
        },
        # Celery worker file
        "celery_worker_file": {
            "class": "logging.handlers.WatchedFileHandler",
            "filename": os.path.join(LOG_DIR, "celery-worker.log"),
            "formatter": "verbose",
            "level": "INFO",
        },
        # Optional: task logger file (if you want separate)
        "celery_task_file": {
            "class": "logging.handlers.WatchedFileHandler",
            "filename": os.path.join(LOG_DIR, "celery-tasks.log"),
            "formatter": "verbose",
            "level": "INFO",
        },
        # Errors (shared)
        "errors_file": {
            "class": "logging.handlers.WatchedFileHandler",
            "filename": os.path.join(LOG_DIR, "errors.log"),
            "formatter": "verbose",
            "level": "WARNING",
        },
    },
    "loggers": {
        # Django app
        "django": {
            "handlers": ["django_file", "errors_file"],
            "level": "INFO",
            "propagate": False,
        },
        # Celery top-level logger
        "celery": {
            "handlers": ["celery_worker_file", "errors_file"],
            "level": "INFO",
            "propagate": False,
        },
        # Celery worker internals
        "celery.worker": {
            "handlers": ["celery_worker_file", "errors_file"],
            "level": "INFO",
            "propagate": False,
        },
        # Task loggers (when you use get_task_logger) #  was celery_task_file
        "celery.task": {
            "handlers": ["celery_task_file", "errors_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# from logging.config import dictConfig
# dictConfig(LOGGING)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-qk=zw&3h@zoe10btbj((u^v8%%2m)x%p(i(f+l!g5hgqvz1-51"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS: list[str] = os.getenv(
    "DJANGO_ALLOWED_HOST", "127.0.0.1,.localhost,[::1],0.0.0.0"
).split(",")

CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "backend.project.apps.ProjectConfig",
    "backend.organisation.apps.OrganisationConfig",
    "backend.researcher.apps.ResearcherConfig",
    "backend.activity.apps.ActivityConfig",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
PRODUCTION_MODE = os.getenv("PRODUCTION_MODE", "False").lower() == "true"

if PRODUCTION_MODE:  # Use postgresql for prod
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": os.getenv("POSTGRES_HOST"),
            "PORT": os.getenv("POSTGRES_PORT"),
        }
    }
else:  # Use sqlite for dev
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/django_static/"
STATIC_ROOT = BASE_DIR / "django_static"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Phenomate settings
DEFAULT_ROOT_FOLDER = os.getenv("DEFAULT_ROOT_FOLDER", os.getenv("HOME", "/home")) + "/Phenomate"
