# Generated by Django 5.2.4 on 2025-07-28 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
        ('project', '0001_initial'),
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.organisation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='researcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researcher.researcher'),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
