# Generated by Django 5.2.4 on 2025-07-31 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("COPY", "Copied"),
                            ("PREPROC", "Preprocessed"),
                            ("REMOVE", "Removed"),
                        ],
                        default="COPY",
                    ),
                ),
                ("filename", models.CharField()),
                ("target", models.CharField(default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("ERROR", "Error"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="QUEUED",
                    ),
                ),
                ("error_log", models.CharField(default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="activity.activity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.project"
                    ),
                ),
            ],
        ),
    ]
