# Generated by Django 5.2.7 on 2025-11-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='error_log',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='activity',
            name='filename',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
