# Generated by Django 5.2.4 on 2025-07-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                ("name", models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
